import { type Metadata } from 'next';
import './globals.css';
import { headers } from 'next/headers';
import Link from 'next/link';
import { type ReactNode } from 'react';
import { Logo } from '@design-system/svg/Logo';
import { TestFakesProvider } from './testing/TestFakesProvider';
import { getTestFakesFrom } from './testing/TestFakesAdapterService';

export const metadata: Metadata = {
    title: 'Space mission',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    const headersList = await headers();

    return (
        <html lang="en" data-google-analytics-opt-out="">
            <body>
                <TestFakesProvider fakes={getTestFakesFrom(headersList)}>
                    <div className="container mx-auto h-screen" style={{ maxWidth: '640px' }}>
                        <div className="pt-8 md:pt-16 h-full">
                            <div className="py-4 px-10 h-full bg-white border border-gray-200">
                                <header className="pb-8 pt-3">
                                    <Link href="/" className="relative text-lg">
                                        Space Mission
                                        <Logo />
                                    </Link>
                                </header>
                                {children}
                            </div>
                        </div>
                    </div>
                </TestFakesProvider>
            </body>
        </html>
    );
}
